<?php

return [
    'header' => 'SSL Certificate for :domain',
    'generated_by' => 'Generated by MapacheSSL',
    'separator' => '===================================================',
    'files_heading' => 'INCLUDED FILES:',
    'cert_desc' => 'Your SSL certificate (fullchain)',
    'key_desc' => 'Your private key (KEEP SECURE!)',
    'chain_desc' => 'Intermediate certificate chain',
    'info_heading' => 'INFORMATION:',
    'domain_label' => 'Domain: :domain',
    'expires_label' => 'Expires: :expires',
    'issued_by' => 'Issued by: Let\'s Encrypt',
    'nginx_heading' => 'NGINX CONFIGURATION:',
    'apache_heading' => 'APACHE CONFIGURATION:',
    'path_hint' => '/path/to/',
    'important_heading' => 'IMPORTANT:',
    'important_1' => 'Let\'s Encrypt certificates expire in 90 days',
    'important_2' => 'Remember to renew before: :expires',
    'important_3' => 'NEVER share your private_key.pem',
    'thanks' => 'Thanks for using MapacheSSL!',
    'unknown_date' => 'Unknown',
];
