services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mapachessl-app
    restart: unless-stopped
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
      - public_build:/var/www/html/public/build
      - ./storage/app/certificates:/var/www/html/storage/app/certificates
    networks:
      - mapachessl

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mapachessl-queue
    restart: unless-stopped
    command: php artisan queue:work --sleep=3 --tries=1 --timeout=2100
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
      - public_build:/var/www/html/public/build
      - ./storage/app/certificates:/var/www/html/storage/app/certificates
    networks:
      - mapachessl
    depends_on:
      - app

  nginx:
    image: nginx:alpine
    container_name: mapachessl-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - public_build:/var/www/html/public/build
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - mapachessl

networks:
  mapachessl:
    driver: bridge

volumes:
  public_build:
